token: ''

startMessage:
  - 'Привет! Бот создаст нужную круговую диаграмму!'
  - 'Бот принимает запросы в строгом формате:'
  - ''
  - '`Заголовок'
  - ''
  - 'значение:число'
  - 'значение:число`'

exampleRequestMessage:
  - 'Пример запроса:'
  - ''
  - '`Животные'
  - ''
  - 'Олени:10'
  - 'Слоны:50`'